DROP TABLE TRAIN_PREDICTED
@
DROP TABLE TEST_PREDICTED
@
CREATE TABLE TRAIN_PREDICTED(ID INTEGER, DECISION VARCHAR(20))
@
CREATE TABLE TEST_PREDICTED(ID INTEGER, DECISION VARCHAR(20))
@
CREATE OR REPLACE PROCEDURE PREDICT()
BEGIN
INSERT INTO TEST_PREDICTED
WITH INDIVIDUAL AS
(
	select ID,PROB.DECISION,sum(log(PROB.PROB)) as S from vtest INNER JOIN PROB ON vtest.value = PROB.VALUE and vtest.col = prob.col group by ID,PROB.DECISION
)
,
TEMP2 AS
(
	SELECT COUNT(*) AS C2 FROM VTRAIN WHERE VALUE='ALL'
),
TEMP1 AS
(
	SELECT COUNT(*) AS C1,DECISION FROM VTRAIN WHERE VALUE='ALL' group by DECISION
),
TEMP3 AS
(
SELECT ID, TEMP1.DECISION, (log(FLOAT(TEMP1.C1)/TEMP2.C2)+ INDIVIDUAL.S) AS TP FROM TEMP2,INDIVIDUAL INNER JOIN TEMP1 ON TEMP1.DECISION = INDIVIDUAL.DECISION
)
,
TEMP4 AS
(
SELECT ID,MAX(TP) as max FROM TEMP3 GROUP BY ID
)
SELECT TEMP3.ID, TEMP3.DECISION FROM TEMP3 INNER JOIN TEMP4 ON TEMP3.ID = TEMP4.ID WHERE TEMP3.TP = TEMP4.max;

INSERT INTO TRAIN_PREDICTED
WITH INDIVIDUAL AS
(
	select ID,PROB.DECISION,sum(log(PROB.PROB)) as S from vtrain INNER JOIN PROB ON vtrain.value = PROB.VALUE and vtrain.col = prob.col group by ID,PROB.DECISION
)
,
TEMP2 AS
(
	SELECT COUNT(*) AS C2 FROM VTRAIN WHERE VALUE='ALL'
),
TEMP1 AS
(
	SELECT COUNT(*) AS C1,DECISION FROM VTRAIN WHERE VALUE='ALL' group by DECISION
),
TEMP3 AS
(
SELECT ID, TEMP1.DECISION, (log(FLOAT(TEMP1.C1)/TEMP2.C2)+ INDIVIDUAL.S) AS TP FROM TEMP2,INDIVIDUAL INNER JOIN TEMP1 ON TEMP1.DECISION = INDIVIDUAL.DECISION
)
,
TEMP4 AS
(
SELECT ID,MAX(TP) as max FROM TEMP3 GROUP BY ID
)
SELECT TEMP3.ID, TEMP3.DECISION FROM TEMP3 INNER JOIN TEMP4 ON TEMP3.ID = TEMP4.ID WHERE TEMP3.TP = TEMP4.max;


END
@
CALL PREDICT()
@