DROP TABLE PROB
@
CREATE TABLE PROB(COL INTEGER,VALUE VARCHAR(20),DECISION VARCHAR(20),PROB DOUBLE)
@
CREATE OR REPLACE PROCEDURE CALCULATE_PROB()
BEGIN
INSERT INTO PROB
WITH TEMP AS
(
	SELECT COUNT(*) AS C1,COL,VALUE,DECISION from vtrain group by VALUE,DECISION,COL
)
,
TEMP1 AS
(
	SELECT COUNT(*) AS C2,DECISION from vtrain where VALUE='ALL' group by DECISION
)
SELECT TEMP.COL,TEMP.VALUE,TEMP.DECISION,FLOAT(TEMP.C1)/FLOAT(TEMP1.C2) FROM TEMP INNER JOIN TEMP1 ON TEMP.DECISION =TEMP1.DECISION;

INSERT INTO PROB
WITH TEMP AS
(
	SELECT COL,VALUE FROM VTRAIN GROUP BY COL,VALUE ORDER BY COL
),
TEMP1 AS
(
	SELECT COL,DECISION FROM VTRAIN GROUP BY COL,DECISION ORDER BY COL
)
SELECT DISTINCT TEMP.COL,VALUE,DECISION,0.00001 FROM TEMP INNER JOIN TEMP1 ON TEMP.COL = TEMP1.COL WHERE NOT EXISTS (SELECT * FROM PROB WHERE PROB.COL=TEMP.COL AND PROB.VALUE=TEMP.VALUE and PROB.DECISION = TEMP1.DECISION);
END
@
CALL CALCULATE_PROB()
@